build:
	javac P1.java
	javac P2.java
	javac P3.java
	javac Bonus.java
run-p1:
	java -Xmx128m -Xss128m P1
run-p2:
	java -Xmx128m -Xss128m P2
run-p3:
	java -Xmx128m -Xss128m P3
run-p4:
	java -Xmx128m -Xss128m Bonus
clean:
	rm *.class
